# Generated by Django 4.1.2 on 2022-10-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
